### ISSUE TITLE
[Bug]: Infinite shimmers on Explore screens if user opened it after a several minutes

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/Sora-iOS#407] opened 2024-02-07 09:49 UTC
### Steps to reproduce

1. Open the app
2. Wait 5 min
3. Open Explore screen

### Actual behavior

https://github.com/sora-xor/sora-ios/assets/17094492/86856acf-e26d-4ef6-83ca-db2d934b93e8

### Expected behavior

User sees Tokens, Pools and Farms

### Environment

{"label"=>"Stage"}

### OS version

iOS

**Comment by ShlyapkinIN** [comment] 2024-02-13 10:41
Can't reproduce it, looks like was fixed with another bug.

**Closed as completed** 2024-02-13 16:53 UTC
Labels: bug, S2-major
